### ISSUE TITLE
RuntimeError: index out of range at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:191

### ISSUE THREAD

**Issue by lthakur007** [chenxijun1029/DeepFM_with_PyTorch#1]
observing the following error while running deep ctr on the gpu:

Traceback (most recent call last):
  File "main.py", line 31, in <module>
    model.fit(loader_train, loader_val, optimizer, epochs=5, verbose=True)
  File "/root/deepctr/DeepFM_with_PyTorch/model/DeepFM.py", line 153, in fit
    total = model(xi, xv)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/deepctr/DeepFM_with_PyTorch/model/DeepFM.py", line 98, in forward
    fm_first_order_emb_arr = [(torch.sum(emb(Xi[:, i, :]), 1).t() * Xv[:, i]).t() for i, emb in enumerate(self.fm_first_order_embeddings)]
  File "/root/deepctr/DeepFM_with_PyTorch/model/DeepFM.py", line 98, in <listcomp>
    fm_first_order_emb_arr = [(torch.sum(emb(Xi[:, i, :]), 1).t() * Xv[:, i]).t() for i, emb in enumerate(self.fm_first_order_embeddings)]
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/sparse.py", line 118, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1454, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:191

**Comment by cserken** [comment]
hi~
anybody know how to fix this issue?

thanks!

**Comment by leadtoit** [comment]
the same problem~

**Comment by mojirml** [comment]
the same problem~

**Comment by monkeyusage** [comment]
the same problem~

**Comment by ice16** [comment]
same problem

**Comment by lewisbakkero** [comment]
Same issue when using flair0.4.1, pythorch1.1.0 and BertEmbeddings on 2 x NVIDIA Tesla P100

**Comment by zqs01** [comment]
the same problem

**Comment by monkeyusage** [comment]
> the same problem~

I had an issue with the embeddings I fixed it initializing the embedding layer with the right size which is the size of the vocabulary I am using.

when creating your Encoder/Model:

`
self.embed = nn.Embedding(vocab_size, embed_size)
`
I was using a smaller number than my actual vocab_size thus resulting in an error.

**Comment by vinklibrary** [comment]
the same problem

**Comment by RyanAmaudruz** [comment]
same issue

**Comment by marchss** [comment]
same issue here.

**Comment by ganyuqi** [comment]
hi, is anybody fix the problem?

**Comment by anksng** [comment]
Hi, try to inspect the size of your vocabulary , if using the `vocab_size` in the Embedding layer initialization, try to add +1 to it like -> `self.embed = nn.Embedding(vocab_size+1, embed_size)`

**Comment by loretoparisi** [comment]
we have the same problem using LASER bi-LSTM model with `PyTorch 1.0 / Python 3.7`
https://github.com/facebookresearch/LASER

**Comment by shantam21** [comment]
Did anyone get the solution? I'm stuck! just wanted to confirm what vocab_size here means. Does it mean the length of the tokenized words set?

**Comment by shira-g** [comment]
It happened to me when I had out-of-vocabulary words which were assigned a -1 value, and also it happens when you set the vocab-size to a smaller value than the size of the vocabulary + 1

**Comment by chenxijun1029** [comment]
Sorry for answering so late!
  I think I've fixed this bug. The main reason is that  I accumulated offset when iterate feature size in data preprocess, so index of categorial feature is out of embedding size. Please refer to  the update in dataPreprocess.py.
  Also, I've found that I should set the index of coutinous feature as 0, and the value of coutinous feature as its original value instead of 1. Refer to the update of dataset.py for more details.
  Thanks for your attention.

**Comment by loretoparisi** [comment]
@chenxijun1029 in which version this has been fixed? Thank you.

**Comment by Guilherme26** [comment]
Hey guys, I had the same problem. In my case, what happened was that I was presenting the Input (X) and the Output (Y) to the model with len(X) != len(Y) due to an error in a third-party library.

Best regards and good luck!

**Comment by maulberto3** [comment]
> > the same problem~
> 
> I had an issue with the embeddings I fixed it initializing the embedding layer with the right size which is the size of the vocabulary I am using.
> 
> when creating your Encoder/Model:
> 
> `self.embed = nn.Embedding(vocab_size, embed_size)`
> I was using a smaller number than my actual vocab_size thus resulting in an error.

Hi. I too resolved my issue by fixing what @MCSZN suggested.

**Comment by tinaty** [comment]
> Hi, try to inspect the size of your vocabulary , if using the `vocab_size` in the Embedding layer initialization, try to add +1 to it like -> `self.embed = nn.Embedding(vocab_size+1, embed_size)`

Hi, this works. But would you mind providing an explanation for this?

**Comment by anksng** [comment]
> > Hi, try to inspect the size of your vocabulary , if using the `vocab_size` in the Embedding layer initialization, try to add +1 to it like -> `self.embed = nn.Embedding(vocab_size+1, embed_size)`
> 
> Hi, this works. But would you mind providing an explanation for this?


I guess it was a bug, which is now fixed by @chenxijun1029 . 
What I remember is that the error is because embedding_dim must be equal to the vocab size, but when initializing the embedding layer with len(voca_size) it somehow subtracts 1.

**Comment by tinaty** [comment]
> > > Hi, try to inspect the size of your vocabulary , if using the `vocab_size` in the Embedding layer initialization, try to add +1 to it like -> `self.embed = nn.Embedding(vocab_size+1, embed_size)`
> > 
> > 
> > Hi, this works. But would you mind providing an explanation for this?
> 
> I guess it was a bug, which is now fixed by @chenxijun1029 .
> What I remember is that the error is because embedding_dim must be equal to the vocab size, but when initializing the embedding layer with len(voca_size) it somehow subtracts 1.

got it. thanks very much.

**Comment by ly1ex** [comment]
same issue

**Comment by lu161513** [comment]
> Hi, try to inspect the size of your vocabulary , if using the `vocab_size` in the Embedding layer initialization, try to add +1 to it like -> `self.embed = nn.Embedding(vocab_size+1, embed_size)`

Why +1 will solve the problem,The initialization of embedding should not be used vocab_size rather than vocab_size+1?

**Comment by onlyhebo** [comment]
I have the same issue.  See `DeepFM_with_PyTorch/data/dataset.py` Row7 : `continous_features = 13`. 
Change the value for your dataset. You can have a correct result.
